### PR TITLE
Updated account type tool tip

### PR DESCRIPTION
**Pull request by eskil0312**

### CODE REVIEW

**Comment by HansDahle** [comment]
Did we not talk about including the more descriptive text as well in the tool tip?

**Comment by eskil0312** [comment]
@HansDahle  I don't recall talking about it, but I guess that could be added as well

**Comment by HansDahle** [comment]
> 
> 
> @HansDahle I don't recall talking about it, but I guess that could be added as well

Should have read the userstories ;)

**Comment by eskil0312** [comment]
> > @HansDahle I don't recall talking about it, but I guess that could be added as well
> 
> Should have read the userstories ;)

😄

**Pull request merged**
